### ISSUE TITLE
Settings or automatic addition of functions/actions

### ISSUE THREAD

**Issue by SuperGNUS** [Parabeac/Parabeac-Core#101]
## Change Proposal
Add the ability for widget to add Onclick(), OnHover(), OnRelease(), OnPress() as separate overridable class that can be passed as a parameter.

### Module and Current Solution
Generation Service - No solution currently.

## Benefits of the Change
If we generate a functions.dart class and can pass that as an optional parameter to the widget we can update the state for instance a TextStyle change when the mouse hovers over the widget.  Improves scalability and Readability and helps with generator not overwriting your changes.

**Comment by SuperGNUS** [comment]
Maybe this needs to be an egg to add gestures to widgets?

https://flutter.dev/docs/development/ui/advanced/gestures

**Comment by siliconivan** [comment]
Yeah I'm not quite sure how to handle hotspots and interpret those as gestures rather than navigation. The only way is through eggs I think.

**Comment by siliconivan** [comment]
This will likely be introduced as an egg in the State management release.
