### ISSUE TITLE
Figma output dimensions of certain widgets are incorrect.

### ISSUE THREAD

**Issue by x64Eddie** [Parabeac/Parabeac-Core#108]
All the media queries in here should be less or equal to 1. Right now, many of the widgets have a constant bigger than 1.

![image](https://user-images.githubusercontent.com/29381845/95633292-98a5f900-0a44-11eb-9760-1f7547de447b.png)

**Comment by akhil2000mittal** [comment]
I can help you with that please can you share more info

**Comment by siliconivan** [comment]
Hey @akhil2000mittal, we'd love for you to jump in on Parabeac-Core. @SushiRoll53 is currently leading this issue, but if you'd still like to jump in, it may be best to join us on a coding session in the Discord server.

**Comment by SushiRoll53** [comment]
This was fixed in a previous release of Parabeac-core.
