### ISSUE TITLE
Generated main.dart remains empty when writer is closed before buffer flush

### ISSUE THREAD

**Issue by roel-de-vries** [Parabeac/Parabeac-Core#111]
When you run parabeac to generate a new project based on a sketch a main.dart is created. `PBFlutterWriter.writeMainScreenWithHome()` opens a writeOnly sink which replaces the original default main.dart created by `flutter create` with an empty one, and then tries to write the parabeac version. But if the program is too fast the sink is closed before the buffer is emptied, resulting in an empty main.dart.

**Comment by roel-de-vries** [comment]
Solution is fairly simple by adding a flush before the close, I have a fix ready :)

**Comment by siliconivan** [comment]
Awesome, I'll assign it! Thanks!
