### ISSUE TITLE
Add documentation on how to get developing on Windows through WSL 2

### ISSUE THREAD

**Issue by roel-de-vries** [Parabeac/Parabeac-Core#115]
Although parabeac-core development on Windows is possible, it currently requires quite some setup.
A documented guide on how to set this up with the help of [WSL 2](https://docs.microsoft.com/en-us/windows/wsl/about) would help others to get starting.

**Comment by roel-de-vries** [comment]
As discussed in the Parabeac discord, I'll get starting on this this week 😄

**Comment by siliconivan** [comment]
Thanks Roel! I assigned it now, let us know if we can help with anything!
