### ISSUE TITLE
Using Dart's ArgParser to parse arguments

### ISSUE THREAD

**Issue by ivan-015** [Parabeac/Parabeac-Core#12]
Currently in both `parabeac.dart` and `main.dart` the arguments are being parsed using a for-loop and a switch statement. This can lead to many errors when parsing arguments and can be quite inefficient.

In order to improve this we can use the [args](https://pub.dev/packages/args) package which provides elegant argument-parsing functionality, reduces the potential for errors, and will make the code more concise.

**Comment by ivan-015** [comment]
![Annotation 2020-08-28 162218](https://user-images.githubusercontent.com/42812006/91619660-f37b0980-e94a-11ea-8250-f5f503309e88.jpg)
The above image is a screenshot of the current argument parsing in `main.dart`

**Comment by snwagbata** [comment]
I'll handle this. Please assign.

**Comment by x64Eddie** [comment]
> I'll handle this. Please assign.

Done 👍🏼

**Comment by siliconivan** [comment]
This should've been closed.
