### ISSUE TITLE
Add how to generate the .g files inside of Parabeac-Core

### ISSUE THREAD

**Issue by siliconivan** [Parabeac/Parabeac-Core#131]
Developers are requesting this so that they don't have to hand edit the .g files inside of Parabeac-Core manually.

**Comment by siliconivan** [comment]
@x64Eddie this was added to the Release 1.3 milestone but I can't find where it is, can you point me in the right direction or was this never completed?

**Comment by x64Eddie** [comment]
@siliconivan, I believe I never completed it; I did not get a chance to loop back and tackle the task.
