### ISSUE TITLE
Dependencies Writer [Integration Testing]

### ISSUE THREAD

**Issue by SushiRoll53** [Parabeac/Parabeac-Core#150]
**Input:** A dependency was requested by a plugin
**Output:** that same dependency on the pubspec.yaml
**Description:** Check that it creates all requested dependencies, even if we have 1 or many

**Comment by SuperGNUS** [comment]
For imports, I just changed the List<String> to a Set<String> which prevents duplicates.  Probably should do the same thing for this test.
