### ISSUE TITLE
Update Docs to reflect Testing

### ISSUE THREAD

**Issue by ivan-015** [Parabeac/Parabeac-Core#156]
## Change Proposal
The change proposes a change in the documentation to reflect testing for the `FIG_API_KEY` environment variable needed to run `pub run test` locally

### Module and Current Solution
This change will only affect the docs. No code should be modified.

## Benefits of the Change
This change will allow users to run the Figma tests locally using their own Figma API key.

**Comment by Ihuds577** [comment]
Reminder: Make sure to remove hacktoberfest and October related content from the docs and readme
