### ISSUE TITLE
Flutter Export is inconsistent with using point values & MediaQuery values

### ISSUE THREAD

**Issue by siliconivan** [Parabeac/Parabeac-Core#169]
## **Describe the bug**
Some Flutter elements are using point values instead of MediaQuery where they should be using MediaQuery. 

## **To Reproduce**
1. Run Parabeac-Core from stable on the demo Sketch File.
2. Visit the generated file landing_page.dart
3. Visit the SignUp Button vs. Log In Button. Here you will see one button is generated with point values & the other is generated with MediaQuery.

## **Impact of the problem**
Parabeac-Core needs to be consistent in the way we export, developers need to have predictability when using Parabeac-Core.

## **Environment:**
macOS Catalina

**Comment by Super-Genius** [comment]
In actuality, you should remove all MediaQuery values and use BoxConstraints for everything.

**Comment by siliconivan** [comment]
That's a good point, we should definitely replace this approach with BoxConstraints. In the meantime, just to get better fidelity, I'll try fixing this. Thanks @klhurley
