### ISSUE TITLE
Aggregate a node's variations and states within its AuxiliaryData

### ISSUE THREAD

**Issue by x64Eddie** [Parabeac/Parabeac-Core#184]
## Feature
After the Parabeac-Core's ingestion phase, all the data regarding _variations_ and _states_ should be aggregated within its `PBIntermediateNode`. This class should contain everything necessary for the Generation Phase to generate code conforming to the state management of choice

Finally, there should be additional attributes that should be refactored out of the `PBIntermediateNode` class into the AuxiliaryData class.

[AB#354](https://dev.azure.com/Parabeac-Main/8bea2d9b-cefd-40f4-82e9-37ff48e11119/_workitems/edit/354)

**Comment by siliconivan** [comment]
I'll take this one @ivan-015.
