### ISSUE TITLE
Unhandled exception during conversion

### ISSUE THREAD

**Issue by malammouri2020** [Parabeac/Parabeac-Core#188]
Got the below exception / Trails while converting Sketch file:
Main: [INFO] - [-p, /Users/user187838/Downloads/Ezipart_Seller.sketch, -n, xxxxxxxx]

SketchController: [ERROR] - type 'double' is not a subtype of type 'int'

lib/main.dart: Warning: Interpreting this as package URI, 'package:parabeac_core/main.dart'.
Unhandled exception:
NoSuchMethodError: The getter 'miscPages' was called on null.
Receiver: null
Tried calling: miscPages
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      Interpret.interpretAndOptimize (package:parabeac_core/controllers/interpret.dart:55:14)
#2      SketchController.convertFile (package:parabeac_core/controllers/sketch_controller.dart:31:38)
#3      main (package:parabeac_core/main.dart:140:30)
#4      _RootZone.runUnary (dart:async/zone.dart:1450:54)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#8      Future._complete (dart:async/future_impl.dart:519:7)
#9      _StreamIterator._onDone (dart:async/stream_impl.dart:1087:20)
#10     _RootZone.runGuarded (dart:async/zone.dart:1372:10)
#11     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
#12     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:420:15)
#13     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:305:7)
#14     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:97:11)
#15     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
#16     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
#17     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:305:20)
#18     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
#19     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:142:24)
#20     _RootZone.runGuarded (dart:async/zone.dart:1372:10)
#21     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
#22     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:420:15)
#23     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:305:7)
#24     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:816:19)
#25     _StreamController._closeUnchecked (dart:async/stream_controller.dart:671:7)
#26     _StreamController.close (dart:async/stream_controller.dart:664:5)
#27     _Socket._onData (dart:io-patch/socket_patch.dart:2051:21)
#28     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#29     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#30     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#31     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#32     _StreamController._add (dart:async/stream_controller.dart:682:7)
#33     _StreamController.add (dart:async/stream_controller.dart:624:5)
#34     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1587:35)
#35     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1069:18)
#36     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#37     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#38     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

**Comment by siliconivan** [comment]
Interesting, thanks for creating an issue. It looks like converting Sketch to PBDL failed. Would you happen to be able to share a section of the sketch file you're using so that I can replicate? @malammouri2020 I imagine it's that error that SketchController is throwing but I'm not sure which class is throwing that.

**Comment by malammouri2020** [comment]
Sure Ivan. Please share email ID to send privately. I will share the file tomorrow.

By the way, this sketch file has been converted from XD file using online xd2sketch tool.

**Comment by siliconivan** [comment]
Sweet! You can send it to ivanh@parabeac.com
