### ISSUE TITLE
Prototyping support for Figma.

### ISSUE THREAD

**Issue by ivan-015** [Parabeac/Parabeac-Core#198]
## Change Proposal
Currently there is no support for Prototyping when converting Figma files. 
### Module and Current Solution
There is no current solution for Figma. There is however, an implementation from Sketch that could be useful. When doing prototyping in sketch, the JSON artboards will have a property that indicates whether the artboard is `home screen`. In addition, in Sketch it is possible to extract `flows` from an element which indicate what page the app should navigate to when the element is clicked.

## Benefits of the Change
Adding this will allow us to have more complete Flutter project exports and extra support for converting Figma files.

AB#510

**Comment by haardikdharma10** [comment]
Hi @ivan-015, can you help me with the files involved and more clarity on how it is to be refactored?

**Comment by ivan-015** [comment]
Hey @haardikdharma10 , sure thing! One of the good things about this issue is that the feature is already implemented for sketch, so you can take a look on how we implemented that on sketch for some additional context, here are the relevant files (sketch-side):
* On `lib/input/sketch/entities/layers/artboard.dart` line 76, we assign the property `isFlowHome`. This property comes directly from the Sketch JSON and tells us if our application will start at the "current" screen. Then, in line 149 we pass that value to the `InheritedScaffold` where it is further handled automatically.
* Almost every sketch element has the `Flow` property. This will tell us if the element we're looking at causes the application to navigate to another screen. For example, in the file `lib/interpret_and_optimize/entities/inherited_container.dart`, on line 64 we check if the element being generated has what we call a `prototypeNodeUUID`, which essentially tells us if this element triggers a transition to another screen. If `prototypeNodeUUID` is not null, we create a new `PrototypeNode` that will be generated as a GestureDetector that takes us to another screen.

For figma, here's what we need to do:
* `lib/input/figma/entities/layers/frame.dart`, line 130. Currently, the `isHomeScreen` property is always set to false. we need to be able to analyze the Figma's JSON element to determine whether the frame we're looking at is a home screen or not. Here, there should be something similar to the `isFlowHome` property from sketch that tells us whether this will be the home screen.
* For Figma elements we need to make sure that if an element has prototyping enabled, it is picked up by parabeac-core and redirects the user to the proper screen. For example, in the image below, there is a button in `LearningOverviewAlt` that takes you to `HomeScreenAlt`. When generating the project through parabeac-core, we should see a GestureDetector in `LearningOverviewAlt` that when pressed takes you to `HomeScreenAlt`. This should be implemented already, but we just need to make sure it works in tandem with the `isHomeScreen` changes.

![image](https://user-images.githubusercontent.com/42812006/103035334-56a93100-4524-11eb-85da-39cd3a62985f.png)


I know that's a lot of information, so please do let me know if you need me to clarify anything. I'm also available on Discord if you need to hop on a call or ask questions there. Thank you!
