### ISSUE TITLE
Stack reduction to Container(child: Container) is not working

### ISSUE THREAD

**Issue by siliconivan** [Parabeac/Parabeac-Core#20]
This seems to be an issue relating to the post-layout rules. The attached photo shows a Stack with a background container & another container. It should've been reduced to a Background Container holding the Text Container. Another issue but unrelated is in the Login button. You can see that the alignment service did not inject a Positioned for the relationship between the Stack & its children which resulted in incorrect looking UI.

<img width="800" alt="Screen Shot 2020-09-14 at 4 31 04 PM" src="https://user-images.githubusercontent.com/13757212/93145556-d4e67380-f6a9-11ea-8d67-2bb98182c8a7.png">

<img width="722" alt="Screen Shot 2020-09-14 at 4 35 32 PM" src="https://user-images.githubusercontent.com/13757212/93145415-7caf7180-f6a9-11ea-91be-be6b698a69d2.png">

**Comment by siliconivan** [comment]
I raised the priority of this given the discussions around screens that are not mobile. UI is much more off than it should be.

**Comment by haardikdharma10** [comment]
@siliconivan, I'd be happy to fix this. Any starting steps you'd like to suggest? Additionally, if you can roughly help me on what needs to be done will be great:)

**Comment by siliconivan** [comment]
That's crazy, we were going to give this one a shot this week but definitely open to giving you first dibs if you'd like. We're not quite sure what the issue is because theoretically all the 'rules' are there. So it'll take some debugging and trying to find the problem. All this will have to do with the layout service which is in the wiki. If you can, we can touch on this in our meetup tomorrow. @x64Eddie is the expert on this service, he's also on Discord.

**Comment by haardikdharma10** [comment]
Sure thing then, we can have a word on Discord.

**Comment by siliconivan** [comment]
Hey @haardikdharma10 I wanted to check in to see how this was going, I know this is a challenging task, but it is definitely a high priority one. Should I reassign the issue?

**Comment by haardikdharma10** [comment]
Heyy @siliconivan, Sorry for not staying on top of this. I am stuck up with my university exams and can promise to be back after a week. Will connect with you over discord to discuss about this more.
