### ISSUE TITLE
Background color isn't detected for figma project

### ISSUE THREAD

**Issue by Ihuds577** [Parabeac/Parabeac-Core#201]
## **Describe the bug**
When converting a figma file, the background color for some (possibly all) screens was not detected. Background color was white but was rendered to black. 

## **To Reproduce**
Just converted the Figma File associated, simply left out the background color. 

## **Impact of the problem**
The background color was not present resulting in a pretty drastically different colored application. 

## **Environment:**
 - OS: MacOS X catalina

**Comment by siliconivan** [comment]
This was fixed with a hotfix.
