### ISSUE TITLE
Sketch Images with Shadows cause incorrect sizing.

### ISSUE THREAD

**Issue by siliconivan** [Parabeac/Parabeac-Core#207]
## **Describe the bug**
Currently with the parabeac_demo_alt.sketch file, elements that have shadows that are converted as images export with incorrect sizing. The reason is because Sketch Exporting automatically compensates for the shadows. I am not 100% clear if we have the same issue on Figma yet but it would require it's own dedicated fix as well.

## **To Reproduce**
Run Parabeac-Core stable on parabeac_demo_alt.sketch, you will see the facebook button on `home_screen_alt.dart` that the output doesn't look correct. The blue circle ends up being too small because the shadows make up the compensated space, however, the image is the correct size and is the same size as its nearby element 'Invite Friends'.

## **Impact of the problem**
Causes the fidelity of the output to be incorrect.

## **Screenshots**
With Shadows Exporting from Sketch
![E2661B1C-876F-468C-A528-FC7A1ABBDE51](https://user-images.githubusercontent.com/13757212/103837183-6eb2a180-5048-11eb-908d-6e517e56056a.png)

Without Shadows Exporting from Sketch (Correct)
![E2661B1C-876F-468C-A528-FC7A1ABBDE512](https://user-images.githubusercontent.com/13757212/103837785-ac172f00-5048-11eb-99fd-4ac44e87d5e2.png)

## **Suggested Fix**
Because this has more to do with the way Sketch exports images, I believe the best thing would be to compensate for this in Sketch Asset Converter. We could temporarily change the Sketch file by removing the shadows on the element we are grabbing as an image, and then add the shadows back to prevent any real modification to the original Sketch file, or we can temporarily create a new file with the element shadowless for the export.

AB#509

**Comment by x64Eddie** [comment]
Fixed in Sketch Asset Converter.
