### ISSUE TITLE
Failed at compilation

### ISSUE THREAD

**Issue by faridg18** [Parabeac/Parabeac-Core#285]
Just cloned the project and tried running 

```
dart parabeac.dart -p /Users/faridgarciayala/Desktop/Parabeac-Core/test/assets/SymbolTest-simp.sketch  -n test
```

I got the following error: 

Align Generator: [ERROR] - NoSuchMethodError: The method 'addImport' was called on null.
Receiver: null
Tried calling: addImport("package:auto_size_text/auto_size_text.dart")

Project Builder: [ERROR] - ProcessException: No such file or directory
  Command: flutter create /Users/faridgarciayala/Desktop/Parabeac-Core/test/assets/test

Provider: [INFO] - Thanks for trying our state management configuration that is now in Beta!
If you run into any issues please feel free to post it in Github or in our Discord!
Provider: [INFO] - Setting up the directories

Align Generator: [ERROR] - NoSuchMethodError: The method 'addImport' was called on null.
Receiver: null
Tried calling: addImport("package:auto_size_text/auto_size_text.dart")

lib/main.dart: Warning: Interpreting this as package URI, 'package:parabeac_core/main.dart'.
Unhandled exception:
FileSystemException: Cannot open file, path = '/Users/faridgarciayala/Desktop/Parabeac-Core/test/assets/test/pubspec.yaml' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:539:18)
#3      _File.readAsStringSync (dart:io/file_impl.dart:584:18)
#4      _File.readAsLinesSync (dart:io/file_impl.dart:590:36)
#5      PBFlutterWriter.submitDependencies (package:parabeac_core/generation/generators/writers/pb_flutter_writer.dart:71:38)
#6      GenerationConfiguration._commitDependencies (package:parabeac_core/generation/generators/value_objects/generation_configuration/pb_generation_configuration.dart:155:14)
#7      GenerationConfiguration.generateProject (package:parabeac_core/generation/generators/value_objects/generation_configuration/pb_generation_configuration.dart:122:11)
<asynchronous suspension>
#8      ProviderGenerationConfiguration.generateProject (package:parabeac_core/generation/generators/value_objects/generation_configuration/provider_generation_configuration.dart:30:17)
#9      FlutterProjectBuilder.convertToFlutterProject (package:parabeac_core/generation/flutter_project_builder/flutter_project_builder.dart:127:35)
<asynchronous suspension>
#10     Controller.convertFile (package:parabeac_core/controllers/controller.dart:55:15)
<asynchronous suspension>
#11     SketchController.convertFile (package:parabeac_core/controllers/sketch_controller.dart:37:17)
#12     main (package:parabeac_core/main.dart:166:24)
#13     _RootZone.runUnary (dart:async/zone.dart:1450:54)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#17     Future._complete (dart:async/future_impl.dart:519:7)
#18     _StreamIterator._onDone (dart:async/stream_impl.dart:1087:20)
#19     _RootZone.runGuarded (dart:async/zone.dart:1372:10)
#20     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
#21     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:420:15)
#22     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:305:7)
#23     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:97:11)
#24     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
#25     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
#26     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:305:20)
#27     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
#28     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:142:24)
#29     _RootZone.runGuarded (dart:async/zone.dart:1372:10)
#30     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
#31     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:420:15)
#32     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:305:7)
#33     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:816:19)
#34     _StreamController._closeUnchecked (dart:async/stream_controller.dart:671:7)
#35     _StreamController.close (dart:async/stream_controller.dart:664:5)
#36     _Socket._onData (dart:io-patch/socket_patch.dart:2051:21)
#37     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#38     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#39     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#40     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
#41     _StreamController._add (dart:async/stream_controller.dart:682:7)
#42     _StreamController.add (dart:async/stream_controller.dart:624:5)
#43     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1587:35)
#44     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1069:18)
#45     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#46     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#47     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

AB#755

**Comment by ivan-015** [comment]
According to your logs, parabeac-core could not find "flutter create". Have you ensured you have flutter installed and in your PATH?
Additionally, have you verified that the path to your sketch file is correct?

**Comment by SuperGNUS** [comment]
I tried and it is breaking inside the code and doesn't have anything to do with flutter.

the 'source.managerData' for a particular node when processing that file is null

![Screen Shot 2021-02-25 at 2 45 26 PM](https://user-images.githubusercontent.com/71915886/109229438-25ddb600-7778-11eb-9d91-0bbdc62a536c.png)


Ken

**Comment by SuperGNUS** [comment]
breaks on dev and stable

**Comment by ivan-015** [comment]
For context, this issue may have to do with running parabeac-core on Big Sur, since it works well for Catalina.

In addition, it's worth noting that the environment in which the error is caused is using both Z-shell terminal and bash terminal with .bashrc and .zshrc files in the home directory.

The error is thrown when trying to run dart's `Process.runSync()` method. When copying the command that fails from the error message (`flutter create <valid/path/to/project>`) and running it on a separate terminal, the command runs successfully. 

Therefore, this may be an issue of dart's `Process` class rather than an issue with parabeac-core
