### ISSUE TITLE
IOS pods file not generate 

### ISSUE THREAD

**Issue by gautamchauhan1702** [Parabeac/Parabeac-Core#296]
## Change Proposal
Not Generate IOS file at project creation time.

### Module and Current Solution
if you project clone time initially run cocoa-pod installation.

## Benefits of the Change
Some new user not identify why IOS pod file not created.

**Comment by siliconivan** [comment]
Thanks @gautamchauhan1702, I'm trying to understand what exactly the issue was. When you ran pod install on the exported project, did you receive an issue with Cocoa pods?

**Comment by gautamchauhan1702** [comment]
@siliconivan Right Sir
successfully create project After  i run cocoa-pods  install process then create IOS pod Files
Good Innovation 
One thing are added 
- If You Add TextField future because design i add textfield but code creation time this textfield take as Line or Box

**Comment by siliconivan** [comment]
Really strange, could we see a screenshot of what was in your design file? @gautamchauhan1702
