### ISSUE TITLE
Project Not Create using Figma File

### ISSUE THREAD

**Issue by gautamchauhan1702** [Parabeac/Parabeac-Core#297]
## **Describe the bug**
dart parabeac.dart -f <Figma File ID> -k <Figma Token Key> -o /Users/lw-37/Desktop ("This Path To Create new Project")
And Give Sometime 
Error "Main: [ERROR] - File was not retrieved from Figma."
And Create two Folder "temp" and "pngs"

## **Impact of the problem**
Project Not Create using Figma File.

## **Environment:**
 - OS: MacOs Catalina 10.15.7

## **Screenshots**
![Screenshot 2021-03-05 at 1 42 00 PM](https://user-images.githubusercontent.com/73827950/110087090-36fe7680-7db9-11eb-9dc5-94619a0459b1.png)
![Screenshot 2021-03-05 at 1 42 15 PM](https://user-images.githubusercontent.com/73827950/110087112-3e258480-7db9-11eb-95a1-a98c22b68f37.png)

## **Additional comments/context:**
Please Provide video for how to implements with figma file.

**Comment by ivan-015** [comment]
Hi @gautamchauhan1702 thanks for reporting this issue. According to the way you ran parabeac-core (`dart parabeac.dart -f -k -o /Users/lw-37/Desktop`), you are missing arguments for the `-f` and `-k` options. To run parabeac-core using Figma, the command should look something like this: `dart parabeac.dart -f <FIGMA_FILE_ID> -k <YOUR_FIGMA_API_KEY> -o /Users/lw-37/Desktop`

If you are unsure on how to get your figma file id or your API key, please refer to the `Running the Conversion` section of our README [here](https://github.com/Parabeac/Parabeac-Core#running-the-conversion)

If you need a Figma file to test with, click [here](https://www.figma.com/file/cmaAGe2hwCp7A5pmEQ2C80/parabeac_demo_fig?node-id=0%3A1)

If you are still having issues, please don't hesitate to leave another comment. Alternatively, reach out to us on our [Discord](https://discord.gg/X4tqeCMK) for faster support or if you want to hop on a quick voice call to get your issues sorted!
