### ISSUE TITLE
Adding a symbol instance to a symbol master causes errors

### ISSUE THREAD

**Issue by ivan-015** [Parabeac/Parabeac-Core#306]
## **Describe the bug**
Adding a symbol instance to a symbol master causes issues, specifically for state management. As an example, take the following sketch file:
![Screen Shot 2021-03-10 at 5 57 14 PM](https://user-images.githubusercontent.com/42812006/110719406-0d36bc80-81ca-11eb-9fde-ea0d9c3db8bf.png)

In the image above it is possible to see that `SmallMajorCard/default` is a Symbol Master that has a Symbol Instance named `buttonIcon` inside of it. This Symbol Instance points to `RoundIcon/LoveGray`. Similarly, `SmallMajorCard/loved` is a Master that has an Instance that points to `RoundIcon/LoveRed`. 

For bloc state management configuration, the following generates:

![image](https://user-images.githubusercontent.com/42812006/110720818-7b7c7e80-81cc-11eb-8a06-817438739cbe.png)

As seen in the image, RoundIconLoveGray() is detected as a symbol instance. However, `RoundIconLoveGray` is itself a bloc component with its own bloc, event, and state.

![image](https://user-images.githubusercontent.com/42812006/110720912-a666d280-81cc-11eb-914d-8295e7f268fd.png)

A similar issue happens with Provider, where small_major_card.dart "thinks" `RoundIconLoveGray` is a simple instance when it is in fact a model itself.

This occurs because `SmallMajorCard` is processed first. Because `RoundIcon` has not yet been processed, it does not get detected as a possible state management instance. However, even if it did, it is unclear to me if bloc states can themselves contain bloc components inside, or if a Provider `ChangeNotifier` can itself contain the states of other models..

## **To Reproduce**
1. Download the [parabeac_demo_alt.sketch](Sketch) demo file.
2. Run Parabeac-Core with `Provider` or `Bloc` configurations.
3. Once the generation is finished, go to small_major_card; the error should be there as a reference to `RoundIconLoveGray`

## **Impact of the problem**
Using Symbol Instances inside Symbol Masters seems to be a relatively intuitive way to build design files. Using this technique along with state management causes incorrect generation of code.

## **Environment:**
 - OS: macOS

## **Screenshots**
Provided above where relevant

**Comment by SuperGNUS** [comment]
I think we should give to Farid.  I think my code updates solve this problem, but it still doesn't solve the passing of constraints to the symbol instances in a master.

And I tried to merge/rebase onto dev but needed to manually merge 3 files and had other priorities, going to try again this weekend
