### ISSUE TITLE
project missing an android/AndroidManifest.xml?

### ISSUE THREAD

**Issue by nithin-dot** [Parabeac/Parabeac-Core#309]
I ran the application in a lib/main.dart and the output said (AndroidManifest.xml could not be found.):
![Error](https://user-images.githubusercontent.com/66895158/111035834-3d889000-8442-11eb-8878-71d63e5f9c41.png)
Would please add an Android folder to run this project

**Comment by ivan-015** [comment]
Hi @nithin-dot , thanks for filing the issue. Please correct me if I'm wrong, but my assumption is that you tried to run Parabeac-Core through Flutter on a mobile device/emulator.

Parabeac-Core is not a Flutter or mobile app, it cannot run on mobile devices. Rather, Parabeac-Core is a Dart command-line application you must run through the terminal or debugger via the `dart` command. Please check out the [Get Started](https://github.com/Parabeac/Parabeac-Core/blob/stable/README.md#get-started) section of our README for more information on how to run it!

If you need help running Parabeac-Core don't hesitate to reach out here, or on our [Discord](https://discord.gg/jKJWtsZ) channel 👍🏾
