### ISSUE TITLE
Make Styles optional

### ISSUE THREAD

**Issue by ivan-015** [Parabeac/Parabeac-Core#323]
## Change Proposal
There should be an argument flag `--no-styles` that disables the output of styles from Parabeac-Core's output. Removing the `shared_props.g.dart` should ensure that any references to these variables are also removed.

### Module and Current Solution
Here is an example of the generated styles for parabeac-core's sample project.
<img width="1152" alt="Screen Shot 2021-03-22 at 11 11 10 AM" src="https://user-images.githubusercontent.com/42812006/112029898-51498b80-8aff-11eb-9d12-37224eca6c1d.png">

This change will likely affect Generation Service since the flag will prevent the `documents` folder and files from being exported.

## Benefits of the Change
Give the developer more control of the output.

**Comment by SuperGNUS** [comment]
Actually, I disagree with this.  Why not just only output the file if there are 1+ references?  Right now with this being the default, your code won't output compilable/runnable code at all.

**Comment by ivan-015** [comment]
We will likely re-implement styles being on by default, and only outputting the file if there is at least one reference as I agree with GVTopCoder's comment. This will be done after all the issues with override properties and styles are ironed out.
