### ISSUE TITLE
Failing to convert getting SketchController: [ERROR] - NoSuchMethodError: The method '[]' was called on null. Receiver: null Tried calling: []("alpha")

### ISSUE THREAD

**Issue by trailerzone** [Parabeac/Parabeac-Core#372]
Getting message when I try to convert the sketch file to flutter:

[WARNING]: No semantics found for Tab

[INFO]: Plugin already in file. Skipping...

[INFO]: Done processing!

warning: failed to load external entity "tempout.xml"

Main: [INFO] - Current version: 1.4.4

Main: [INFO] - [-p, /Users/user/AndroidStudioProjects/sketchfiles/leasedcard2.sketch, -n, newproject]

Main: [INFO] - Downloading submodule SketchAssetConverter

SketchController: [ERROR] - NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("alpha")

lib/main.dart: Warning: Interpreting this as package URI, 'package:parabeac_core/main.dart'.
Unhandled exception:
NoSuchMethodError: The getter 'id' was called on null.
Receiver: null
Tried calling: id
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      SketchController.convertFile (package:parabeac_core/controllers/sketch_controller.dart:35:53)
#2      main (package:parabeac_core/main.dart:189:24)
<asynchronous suspension>

dart parabeac.dart -p /Users/user/AndroidStudioProjects/sketchfiles/leasedcard2.sketch -n newproject

It fails to convert the sketch file on Mac Catalina 10.15.7

**Comment by ivan-015** [comment]
Hi @trailerzone , I'd love to help you solve this issue and convert your file. Is it possible for you to post your Sketch file so I can try to convert it and debug?
