### ISSUE TITLE
Figma Support

### ISSUE THREAD

**Issue by x64Eddie** [Parabeac/Parabeac-Core#41]
Supporting Figma designs, being able to generate Flutter code that is derived from a Figma design. This requires:
- Being able to request a Figma Design's JSON from the Figma API using the credentials from the user.
- deserializing the Figma design JSON  to Figma Dart classes, which are going to be mapped to Parabeac's Design Language (PBDL).
- Converting Figma vectors to images.

**Comment by siliconivan** [comment]
This is done.
