### ISSUE TITLE
dartfmt is unable to find directories and causes submitDependencies to fail

### ISSUE THREAD

**Issue by jack-mo** [Parabeac/Parabeac-Core#423]
## **Describe the bug**
`Process.runSync` on `dartfmt` throws an error and causes `PBFlutterWriter.submitDependencies` to stop.
Cause by `dartfmt` not being able to find the directories.

## **To Reproduce**
Generate using sample Figma

## **Impact of the problem**
`PBFlutterWriter.submitDependencies` is stopped in the middle of overwriting the pubspec.yaml file and only half the file is written

## **Environment:**
 - OS: macOS 11.3
 - Flutter: 2.0.6

## **Screenshots**
![Screen Shot 2021-05-14 at 11 22 30 AM](https://user-images.githubusercontent.com/10410579/118292490-af16a600-b4a6-11eb-9074-70c5f4d78d9d.png)

![Screen Shot 2021-05-14 at 11 23 10 AM](https://user-images.githubusercontent.com/10410579/118292568-c5bcfd00-b4a6-11eb-972b-f82a7e99ea0d.png)

## **Additional comments/context:**
Could possibly catch exception from `Process.runSync` in case `dartfmt` fails

**Comment by SushiRoll53** [comment]
Thank you for pointing this out, we will look into this issue right away
