### ISSUE TITLE
Allow relative paths in parameters

### ISSUE THREAD

**Issue by SuperGNUS** [Parabeac/Parabeac-Core#43]
## Change Proposal
Remove necessity of full paths for running Parabeac

### Module and Current Solution
The command line arguments require full paths for running Parabeac, if it instead used arg[0] path and retrieved the full paths of the other arguments that would help automatic builds.

## Benefits of the Change
I could then add my .sketch file to the project and run a script to automatically update the code when it changes.  Right now I have to change directory CD to where Parabeac is located for it to work.

**Comment by roel-de-vries** [comment]
I'd like to give this a try, is it still up for grabs?

**Comment by siliconivan** [comment]
Up for grabs! Assigning it now. Thanks!
