### ISSUE TITLE
Stuck at Installing dependencies

### ISSUE THREAD

**Issue by rayyan808** [Parabeac/Parabeac-Core#443]
After installing Flutter, Dart and node.js, following all intermediate steps. I've tried to run:
`dart parabeac.dart -k <> -f <>`

It begins to install dependencies and has been this way for over an hour. Multiple reboots and network diagnostics were done, but it still won't progress further. 

` Installing Parabeac-core and its dependencies`

**Comment by SushiRoll53** [comment]
Alright, we are going to take a look to this issue. 
Can you tell us which version of Dart & node.js are you using?
Also in which platform are you running it?
