### ISSUE TITLE
Layout not respecting Sizing settings from Sketch

### ISSUE THREAD

**Issue by SuperGNUS** [Parabeac/Parabeac-Core#449]
## **Describe the bug**
When you select different resizing and Alignments, the Layout Generator does not respect the settings from Sketch

## **To Reproduce**
1. Export ExchangeWidget.sketch
2. Notice that GNUS moves to the right because the parent container resizes. It shouldn't resize because the resize is set to fixsize in vertical and horizontal. See screenshot below.  Parent container is set to align middle with fixed sizes set in sketch.

## **Impact of the problem**
Unwanted layouts

## **Environment:**
 - OS: MacOS/Sketch.app

## **Screenshots**
![Sketch Group Container Layout](https://user-images.githubusercontent.com/71915886/120086083-209f4880-c092-11eb-8de0-86930e46f699.png)

![Android Pixel XL mapping](https://user-images.githubusercontent.com/71915886/120086204-b6d36e80-c092-11eb-9f0e-e3abafacea81.png)

![Sketch Mapped to Pixel XL](https://user-images.githubusercontent.com/71915886/120086235-e5e9e000-c092-11eb-8296-2bc58adc714c.png)

## **Additional comments/context:**
Attached is the source sketch file [ExchangeWidget.zip](https://github.com/Parabeac/Parabeac-Core/files/6565377/ExchangeWidget.zip)

**Comment by siliconivan** [comment]
Ah, I'm currently working on addressing the resizing feature, we have not given any thought to Layouts though. Is this what was causing the GNUS to get squished? 🤔

**Comment by siliconivan** [comment]
How we are planning to address this issue: https://www.notion.so/parabeac/Scaled-UI-f258c171dd7f408d968bad67ca1e20b4
