### ISSUE TITLE
Change BLoC middleware output

### ISSUE THREAD

**Issue by SushiRoll53** [Parabeac/Parabeac-Core#464]
## Change Proposal
1.- BLoC structure inside screens should be wrapped on Layoutbuilder, if necesary
 That should also include the if statements for the different states if available. next screen shot shows a draft example.

![Screen Shot 2021-06-10 at 3 31 26 PM](https://user-images.githubusercontent.com/35854816/121603493-15d7a280-ca06-11eb-8e86-1ad6f2cf8633.png)

2.- The output for states on BLoC, should not include any UI, leave it on the bones for now.
3.- Bloc & Event page remain empty for the end developer to fill out

### Module and Current Solution
Most if not all of the changed for this refactor will be under `bloc_middleware.dart`

## Benefits of the Change
It should generate a friendlier BLoC code that should be run with no problem or with small tweaks.

**Comment by ivan-015** [comment]
# Change suggestions for this issue:

## Change Proposal
1. BLoC output shall export a Cubit under the `bloc` folder for each state management node. The name of the file shall be `<component_name>_cubit.dart`. The class name shall be `<component_name>Cubit`.


2. Parabeac-core shall output a template for the `states` of this cubit based on the number of states of the component. These states include an abstract class named `<component_name>State`, and each state of the component shall be a class extending the abstract. For instance, if we have component `SmallMajorCard` with states `default` and `loved`, parabeac-core shall output the following:

    ![Screen Shot 2021-06-11 at 11 19 11 AM](https://user-images.githubusercontent.com/42812006/121725708-da40e500-caa6-11eb-9271-b6cf5b4a828b.png)

> This template may be inside `<component_name>_cubit.dart`


3. Parabeac-core shall output a template for the cubit inside `<component_name>_cubit.dart`. See below for an example:
    ![Screen Shot 2021-06-11 at 11 21 24 AM](https://user-images.githubusercontent.com/42812006/121725973-28ee7f00-caa7-11eb-8f9a-ef5de54b385b.png)

> Notice how `SmallMajorCardCubit` extends `Cubit<SmallMajorCardState>`, and how super is initialized with `SmallMajorCardDefaultState()`. Parabeac-core can initialize the cubit with the state it detects as default to ensure cubits are always initialized with a valid state out of the box.



### Module and Current Solution
Most if not all of the changed for this refactor will be under `bloc_middleware.dart`

## Benefits of the Change
Generate a beginner-friendly BLoC using Cubits that still allows for flexibility and further extension on the developer side after generation.
