### ISSUE TITLE
[Error] Parabeac Core install.sh is throwing an error (Windows)

### ISSUE THREAD

**Issue by alexis084** [Parabeac/Parabeac-Core#48]
Just trying to run Parabeac Core with the sample file provided on the README. Pub install works but when I type the command to run Parabeac Core I get the error below:

CreateProcessW failed 2
Unhandled exception:
ProcessException: The system cannot find the file specified.

  Command: bash C:\Users\alexu\Parabeac-Core/pb-scripts/install.sh

I do have Flutter and the Dart SDK installed correctly.
Anybody else on Windows?

**Comment by ChangJoo-Park** [comment]
Same as this Issue https://github.com/Parabeac/Parabeac-Core/issues/29 . :)

**Comment by Ihuds577** [comment]
As @ChangJoo-Park said this is a duplicate issue of #29. Closing Issue for that reason.
