### ISSUE TITLE
Scaffolds with one element not inheriting a stack for `body:`.

### ISSUE THREAD

**Issue by siliconivan** [Parabeac/Parabeac-Core#485]
Because Scaffolds are not assigning a Stack to wrap a single element screen, we get a bug where there is no alignment or `Positioned:` applied to that element.

Image for example: 
<img width="1792" alt="Screen Shot 2021-07-24 at 12 17 26 PM" src="https://user-images.githubusercontent.com/13757212/126876286-c6770766-d3c7-4de5-9f4d-ed7e5b583817.png">

**Comment by x64Eddie** [comment]
Solved this issue with the following conditional statement in the `pb_layout_generation_service.dart`.

```dart
if (children.length == 1) {
        /// With the support for scaling & pinning, Stacks are now responsible for positioning.
        if (parent is PBIntermediateStackLayout) {
          return parent;
        }
        return _replaceNode(parent, children[0]);
      } 

```
