### ISSUE TITLE
Symbols & Miscellaneous nodes don't scale with screen sizes.

### ISSUE THREAD

**Issue by siliconivan** [Parabeac/Parabeac-Core#49]
## Change Proposal
For Symbols & Miscellaneous nodes, the layout service should default to using Stack layouts. Along with the Stack we should keep track of the resizing option from the design files. Where the Symbol/Misc node is used, we should inject a transform to scale the node to the size needed.

## Unclear/Experiments to be done
It is unclear if forcing a Stack is completely necessary. The first experiment should be around injecting the transform & detecting the resizing option.

## Module and Current Solution
This solution will likely effect the way the layout service works down to generation.

## Benefits of the Change
Better UI Scalability

**Comment by x64Eddie** [comment]
Yeah, I think changing the layout service is unnecessary, we should be able to just use `Transform.scale()`
 is the way to go. We would just have to grab the information on the screen where the symbol is going to be displayed, then scale the symbol relative to the screen. For example, in the screen in the screenshot, I simply just wrapped the symbol instance by `Transform.scale()` and scaled the symbol up.
![examplesymbol](https://user-images.githubusercontent.com/29381845/94378094-d3726d80-00e3-11eb-91c3-2cafcc129a1d.jpg)

**Comment by siliconivan** [comment]
Duplicate of #130, other changes were made relating to this on other issues as well. #130 should fix this though, otherwise we can reopen it.
