### ISSUE TITLE
Improve on text widgets

### ISSUE THREAD

**Issue by SushiRoll53** [Parabeac/Parabeac-Core#50]
## Change Proposal
Change conventional text for: [Auto Size Text in Flutter w/ AutoSizeText Package](https://www.reddit.com/r/FlutterDev/comments/j0or0a/auto_size_text_in_flutter_w_autosizetext_package/?utm_source=share&utm_medium=ios_app&utm_name=iossmf)

### Module and Current Solution
Intermediate Text (looking for the necessary info from the file, such as MAX LINES) and TextGenerator (It should print the new widget)

## Benefits of the Change
What improvements occur because of this change? It would make text more dynamic for apps, so we wont have overflows and text will adapt to the provided space

**Comment by siliconivan** [comment]
Do you think this should be an egg?

**Comment by ChangJoo-Park** [comment]
[auto_size_text](https://pub.dev/packages/auto_size_text) is good package. but result of design resource to code should be same as source of truth. It can not be a default option.

**Comment by siliconivan** [comment]
I suppose it needs to be an egg then.
