### ISSUE TITLE
Detecting the OS that Parabeac is running on and extracting the current directory

### ISSUE THREAD

**Issue by Ihuds577** [Parabeac/Parabeac-Core#56]
## Description
This would allow for Parabeac Core to detect the OS that it is being run in and then based on that information identify the current directory it is in as well. This would be very helpful in helping to support Parabeac Core outside of just Mac and Linux environments as well as help set the groundwork for automatic path usage within Parabeac Core. 

## Files Affected:
* main.dart
* parabeac.dart

**Comment by haardikdharma10** [comment]
Hey @Ihuds577, can I take this?

**Comment by Ihuds577** [comment]
Hey @haardikdharma10, you got it! It's been assigned 👍

**Comment by siliconivan** [comment]
This should've been closed.
