### ISSUE TITLE
Split up _generatescreens method within interpret.dart based on responsibilites

### ISSUE THREAD

**Issue by Ihuds577** [Parabeac/Parabeac-Core#58]
## Description
The method for interpret dart on Parabeac Core is currently very long and functions like a pipe filter, this proposal is to break that into separate methods based on responsibility. 

## Current Solution 
The current structure is just a very long and difficult to read method that handles the entire process of generating screens within the Interpret.dart file

## Proposed Solution
Instead of having all of the logic happen within this function in the interpret.dart file, have this function call other functions that handle the specific task being formed at that point. This would clean up the code and make it a lot easier to both read and maintain going forward.

## Files Affected:
* interpret.dart

## Additional Notes:

**Comment by siliconivan** [comment]
It's not clear to me what you're proposing to change here.🤔

**Comment by haardikdharma10** [comment]
Hey @Ihuds577, can you assign this to me? Thanks:)

**Comment by Ihuds577** [comment]
@haardikdharma10 You got it!

**Comment by siliconivan** [comment]
This issue was fixed with PR: https://github.com/Parabeac/Parabeac-Core/pull/103
