### ISSUE TITLE
Add -h Help Flag for Running Parabeac.dart

### ISSUE THREAD

**Issue by Ihuds577** [Parabeac/Parabeac-Core#59]
## Description
By adding a -h flag when running parabeac.dart users would be able to access a help menu within the terminal giving better information on how to run Parabeac Core as a whole. Also adding this as a default if parabeac.dart is run without any flags or parameters. 

## Files Affected:
* parabeac.dart

## Additional Notes:

**Comment by adamcakg** [comment]
Hi, can you assign me to this ??

**Comment by Ihuds577** [comment]
Hey @adamcakg , this is completely our fault, but we have someone who made a pull request on this issue. We hope you stick around, let us know if you need help with anything! Feel free to join our discord if you want to chat!

**Comment by siliconivan** [comment]
This was done already.
