### ISSUE TITLE
Not all Figma Pages being included in Widgetbook gen.

### ISSUE THREAD

**Issue by siliconivan** [Parabeac/Parabeac-Core#597]
## **Describe the bug**
Not all Figma Pages being included in Widgetbook gen. In this case I believe PB is pulling from two different Figma files because of a component that belongs in the other file, the codegen seems to work correctly as both are generated but specifically in the widgetbook gen it's only generating for one of the pages.

## **To Reproduce**
1. Use this file to generate the code: https://www.figma.com/file/R7GBEc0mfXsJi6B7y3lITe/Parabeac-Widgetbook-Example?node-id=0%3A1
2. Generate Code, you will see "Page 1" as the only folder that shows up in the widget book.

## **Impact of the problem**
Doesn't show 100% of the components that are supposed to be shown.

## **Environment:**
 - macOS
 - Flutter Version - 2.10.0
 - Dar Version - 2.16.0

## **Additional comments/context:**
<img width="1198" alt="Screen Shot 2022-02-22 at 11 35 19 PM" src="https://user-images.githubusercontent.com/13757212/155353604-0508a983-178d-4b7d-baae-aa3ed01e9aa5.png">

**Comment by ivan-015** [comment]
Do you have an example of what other component should be generated for this file? I only see the following: 
<img width="410" alt="image" src="https://user-images.githubusercontent.com/42812006/156039368-7eb338f4-5487-4a3a-8498-ad512e0540f5.png">

**Comment by ivan-015** [comment]
Closing this, as we only currently support components for widgetbook generation. Feel free to reopen if there are any more comments.
