### ISSUE TITLE
[Parabeac Eggs] Parabeac Egg for Date Picker 

### ISSUE THREAD

**Issue by Ihuds577** [Parabeac/Parabeac-Core#62]
## Egg Description
This egg would allow support for the datePicker functionality within buttons automatically. Creating the on click date selection function for a button with the given semantic. 

## Semantic Suggestion:
`.*button.date-picker` or with <> `<button.date-picker>`

## Relevant Widgets:
* Any Button Widget

## Additional Notes:

**Comment by infiniteoverflow** [comment]
I would like to contribute this Egg !!

**Comment by Ihuds577** [comment]
Hey @infiniteoverflow, you got it! Just some additional resources that may help: You can find some details on Parabeac Eggs here, https://github.com/Parabeac/parabeac_eggs. We also have an egg template to help you get started as well (you can find that here https://github.com/Parabeac/parabeac-egg-template). Feel Free to reach out here or on our discord if you have any questions!

**Comment by infiniteoverflow** [comment]
Sure , thanks a lot :)
