### ISSUE TITLE
[Parabeac Eggs] Parabeac Egg for Text Fields

### ISSUE THREAD

**Issue by Ihuds577** [Parabeac/Parabeac-Core#66]
## Egg Description
This egg would allow support for text fields to be generated in the place of general Text widgets. These would be configured to return input when called upon. 

## Semantic Suggestion:
`.*text-field` or with <> `<text-field>`

## Relevant Widgets:
* Text Field 

## Additional Notes:

**Comment by siliconivan** [comment]
This was addressed by @DepressoExpressoBoi . Closing out.
