### ISSUE TITLE
Create FAQ Page in wiki

### ISSUE THREAD

**Issue by siliconivan** [Parabeac/Parabeac-Core#81]
This is a sloppy issue I've began to put together but I will be adding to this as we figure out what should go into the FAQ page. All the suggestions below are from GeniusVentures.

Current questions to address:

- `When converted to symbol the rectangles are hidden, but they are probably still exported and used to figure out that all the text, images, etc are in that rectangle, but that rectangle is not in the the bounds of symbol, so it doesn't use column layout...

This shold be documented in in a FAQ`

- `flutter note, on the kerning feature I just added, they add an extra spacing after the last character.  Kind of sucks, but we could hack around it by changing the width or just put that in our FAQ also.`

- `one more for the FAQ, with kerning on Flutter adds kerning after the last character.  It's supposed to be only between characters, so if your rect is exactly the font rectangle with kerning it will wrap the last letter sometimes.`

**Comment by kichloo** [comment]
@siliconivan Is this issue open to contribution?I would like to work on it.
