### ISSUE TITLE
Update the CONTRIBUTING.MD

### ISSUE THREAD

**Issue by kichloo** [Parabeac/Parabeac-Core#89]
Fix the documentation and update the file

**Comment by kichloo** [comment]
Pl assign this issue to me.

**Comment by x64Eddie** [comment]
What kind of fix are you going to do in the documentation? @kichloo  🤔

**Comment by kichloo** [comment]
@x64Eddie There are some typo fixes required.

**Comment by x64Eddie** [comment]
cool! just make sure you make the PR to the **dev** branch. I'll assign the issue to you! 👍🏼

**Comment by kichloo** [comment]
@x64Eddie Definitely!

**Comment by kichloo** [comment]
@x64Eddie I first did by making it to the `dev` branch but it is including all the previous 19 commits of the users in the PR and thus, giving conflicts. So, I made these changes to the `stable` branch to avoid any conflicts. Hop that's not a problem.
