### ISSUE TITLE
Support for sketch alignment type 2 (wrap text to width and height of text layer)

### ISSUE THREAD

**Issue by SuperGNUS** [Parabeac/Parabeac-Core#98]
Took me a while to figure out why my text wasn't centered in the container.

![Screen Shot 2020-10-05 at 12 38 49 PM](https://user-images.githubusercontent.com/71915886/95124316-13e77200-0708-11eb-83e7-f5913bf3debb.png)

It turns out that Parabeac isn't supporting this in the Paragraph/Text Style.

![Screen Shot 2020-10-05 at 12 37 47 PM](https://user-images.githubusercontent.com/71915886/95124369-2a8dc900-0708-11eb-9c0c-64fd049b5bec.png)

which tightly wraps text by adjusting the baseline from the center vertically in the Fixed Size ![Screen Shot 2020-10-05 at 12 45 10 PM](https://user-images.githubusercontent.com/71915886/95124690-a556e400-0708-11eb-8c27-e16d03f3d3f4.png) in Sketch.

If you select Alignment Auto Height ![Screen Shot 2020-10-05 at 12 46 31 PM](https://user-images.githubusercontent.com/71915886/95124842-e51dcb80-0708-11eb-83ea-ed662ed607b7.png). it increases the size of the bounding box, which you can then move up and in sketch you get a bounding box that accounts for ascent and descent in the font with characters, i.e. lower case 'y' and line spacing.
![Screen Shot 2020-10-05 at 12 47 59 PM](https://user-images.githubusercontent.com/71915886/95126000-9ffa9900-070a-11eb-8146-24b144e6cbcb.png)

Not sure how to solve this yet, but I think [StrutStyle](https://api.flutter.dev/flutter/painting/StrutStyle-class.html) is going to be the answer. 

This setting is what is happening in Parabeac which isn't taking into account the fixed size align vertical setting.  When set to top, you get what you do in Sketch.

![Screen Shot 2020-10-05 at 12 53 49 PM](https://user-images.githubusercontent.com/71915886/95125745-45613d00-070a-11eb-8c8f-55acd6108555.png)

When you set to vertically center align, you still get the same screenshot above.

![Screen Shot 2020-10-05 at 12 54 00 PM](https://user-images.githubusercontent.com/71915886/95125881-6de93700-070a-11eb-9157-15381aa386f7.png)

**Comment by siliconivan** [comment]
I had always wondered why we had these tiny issues around text, I hadn't had the chance to look into it, thanks for looking so deeply into it.
