### ISSUE TITLE
Add LayoutBuilder to Widgets to utilize constraints.

### ISSUE THREAD

**Issue by SuperGNUS** [Parabeac/Parabeac-Core#99]
## Change Proposal
Right now the code uses MediaQuery.Of(context) to set positions, padding, etc.  This should really be using constraints passed in that are the parent container, which is not necessarily the full screen or even the SafeArea()

### Module and Current Solution
Alignment Service will be effected, and we will need to pass constraints parameters to all child widgets (which is good for using symbols).

## Benefits of the Change

What improvements occur because of this change? (Readability, Performance, Scalability, etc...)
Scalability is improved.

**Comment by SuperGNUS** [comment]
This can be closed with pull request #129

**Comment by siliconivan** [comment]
Thanks for the PR link comment.
